In [ ]:
import numpy as np

In [ ]:
a = np.ones((3, 2), dtype=np.uint8)
a

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=uint8)

In [ ]:
d = np.full((3, 3), 6)
d

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [ ]:
b = np.zeros ((3, 2), dtype=np.uint8)
b

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=uint8)

In [ ]:
c = np.array([1, 2, 3, 4, 5, 10, 8])
c

array([ 1,  2,  3,  4,  5, 10,  8])

In [ ]:
arr = np.array([[1, 2, 3, 4, 5, 10, 8],
               [1, 2, 3, 4, 5, 10, 8]])
arr

array([[ 1,  2,  3,  4,  5, 10,  8],
       [ 1,  2,  3,  4,  5, 10,  8]])

In [ ]:
reshape_arr = arr.reshape(2, 3,4)
reshape_arr

ValueError: ignored

In [ ]:
import numpy as np
import pandas as pd

data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

dataFrame = pd.DataFrame(data, columns=['Col1', 'Col2', 'Col3'], index=["Row1", "Row2", "Row3"])

dataFrame.iloc[2] =  0
dataFrame = dataFrame.T
dataFrame


Col1  Col2  Col3
Row1    10    20    30
Row2    40    50    60
Row3     0     0     0

In [ ]:
import numpy as np
from google.colab import autoviz
df_2894648159842276395 = autoviz.get_df('df_2894648159842276395')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_2894648159842276395, *['Col3'], **{})
chart