In [ ]:
import numpy as np

In [ ]:
a = np.ones((3, 2), dtype=np.uint8)

In [ ]:
print (a)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
b = np.full((3, 2), 6)
b

array([[6, 6],
       [6, 6],
       [6, 6]])

In [ ]:
c = np.zeros((3, 2), dtype=np.uint8)
c


array([[0, 0],
       [0, 0],
       [0, 0]], dtype=uint8)

In [ ]:
d = np.array([1, 2, 3, 4, 5, 10, 20, 4])
print(d)

[ 1  2  3  4  5 10 20  4]


In [ ]:
e = np.array([[1, 2, 3, 4],
             [5, 10, 20, 4]]
             )
print(e)

[[ 1  2  3  4]
 [ 5 10 20  4]]


In [ ]:
f = np.array([[1, 2, 3, 4],
             [5, 10, 20, 4],
              [1, 7, 3, 4],
             [5, 10, 320, 4]]
             )
print(np.ndim(f))

2


In [ ]:
f.size

16

In [ ]:
d.dtype

dtype('int64')

In [ ]:
f.reshape(2, 2, 4)

array([[[  1,   2,   3,   4],
        [  5,  10,  20,   4]],

       [[  1,   7,   3,   4],
        [  5,  10, 320,   4]]])

In [ ]:
np.unique(f)

array([  1,   2,   3,   4,   5,   7,  10,  20, 320])

In [ ]:
array1 = np.array([1.0, 2.0, 3.0])
array2 = np.array([1.1, 2.2, 2.9])

# Check element-wise closeness with a tolerance of 0.1
result = np.isclose(array1, array2, atol=0.1)

print(result)

[ True False  True]


In [ ]:
I = np.eye(4, M=None, k=0, dtype='int', order='C')
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
arr = np.array([2, 8, 6, 4, 10])
indices = np.where(arr > 5)
print(indices)


(array([1, 2, 4]),)


In [ ]:
arr1 = np.array([2, 8, 6, 4, 10])
indices1 = np.where(arr1 > 5, arr, 0)
print(indices1)


[ 0  8  6  0 10]
